tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
cask "adoptopenjdk"
brew "awscli"
brew "bash-completion"
brew "elasticsearch", restart_service: true
brew "git"
brew "heroku"
brew "htop"
brew "httpie"
brew "jq"
brew "libtool"
brew "mas"
brew "mongodb/brew/mongodb-community"
brew "postgresql", restart_service: true
brew "pipenv"
brew "redis", restart_service: true
brew "tmux"
brew "wget"
brew "yarn"
brew "zsh"
brew "heroku/brew/heroku"
cask "1password"
cask "dash"
cask "dbeaver-community"
cask "docker"
cask "brave-browser"
cask "flux"
cask "graphql-playground"
cask "iterm2"
cask "licecap"
cask "ngrok"
cask "postman"
cask "tunnelbear"
cask "skype"
cask "sketch"
cask "skitch"
cask "signal"
cask "slack"
cask "spotify"
cask "sync"
cask "tableau"
cask "telegram"
cask "visual-studio-code"
cask "zoom"
mas "DaisyDisk", id: 411643860
mas "Magnet", id: 441258766
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Notebook - Take Notes, Sync", id: 1173152781
