tap "heroku/brew"
tap "homebrew/cask-cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "awscli"
brew "bash-completion"
brew "elasticsearch", restart_service: tru
brew "git"
brew "htop"
brew "httpie"
brew "jq"
brew "mas"
brew "mongodb"
brew "nvm"
brew "postgresql", restart_service: true
brew "python"
brew "redis"
brew "tmux"
brew "wget"
brew "yarn"
brew "zsh"
brew "heroku/brew/heroku"
cask "adoptopenjdk"
cask "anaconda"
cask "1password"
cask "dash"
cask "dbeaver-community"
cask "docker"
cask "brave-browser"
cask "flux"
cask "graphql-playground"
cask "iterm2"
cask "licecap"
cask "ngrok"
cask "postman"
cask "tunnelbear"
cask "skype"
cask "sketch"
cask "skitch"
cask "slack"
cask "spotify"
cask "sync"
cask "tableau"
cask "telegram"
cask "visual-studio-code"
cask "zoom"
mas "Bear", id: 1091189122
mas "DaisyDisk", id: 411643860
mas "Magnet", id: 441258766
